[project]
name = "day09-2a202601035-nguyentranquangmanh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.3.14",
    "langchain-core>=1.5.3",
    "langchain-groq>=1.1.1",
    "langgraph>=1.2.10",
    "python-dotenv>=1.0.1",
]
